# ./render.yaml (VERSÃO FINAL CORRIGIDA)

services:
  # 1. Serviço para o Frontend (React/Vite)
  - type: web
    name: frontend
    runtime: static
    buildFilter:
      paths:
        - lead-import-visualizer/**
    buildCommand: |
      cd lead-import-visualizer &&
      npm install &&
      npm run build
    staticPublishPath: ./lead-import-visualizer/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # 2. Serviço para a API (Backend Laravel)
  - type: web
    name: backend
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile.prod # Certifique-se que o nome do Dockerfile está correto
    buildFilter:
      paths:
        - backend/**
    healthCheckPath: /api/health
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: backend
          property: url
      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend
          property: url
      - key: DB_CONNECTION
        # ATENÇÃO: Se o Render provisionar um MySQL, mude aqui para 'mysql'.
        # Se for PostgreSQL (como definido abaixo), o driver correto é 'pgsql'.
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgres # CORREÇÃO: "psql" alterado para "postgres"
          name: database
          property: internalHost
      - key: DB_DATABASE
        fromService:
          type: postgres # CORREÇÃO: "psql" alterado para "postgres"
          name: database
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgres # CORREÇÃO: "psql" alterado para "postgres"
          name: database
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres # CORREÇÃO: "psql" alterado para "postgres"
          name: database
          property: password
      - fromGroup: laravel-secrets
    startCommand: |
      php artisan migrate --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      /usr/sbin/php-fpm83 -O

  # 3. Serviço de Worker para Filas do Laravel
  - type: worker
    name: queue-worker
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile.prod
    buildFilter:
      paths:
        - backend/**
    startCommand: "php artisan queue:work --verbose --tries=3 --timeout=120"
    envVars:
      - fromGroup: laravel-secrets

  # 4. Banco de Dados Gerenciado
  - type: postgres # CORREÇÃO: "psql" alterado para "postgres"
    name: database
    plan: free

# --- GRUPO DE SEGREDOS ---
envVarGroups:
  - name: laravel-secrets
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          type: web
          name: frontend
          property: url