version: "3.9"

x-app-env: &app-env
  APP_ENV: production
  WWWUSER: '1000'
  APP_DEBUG: 'false'

services:
  mysql:
    image: mysql:8.0
    container_name: leads-mysql
    restart: unless-stopped
    volumes:
      - sail-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 10s
    networks: [sail]

  laravel:
   
    build:
      context: . 
      dockerfile: Dockerfile
    image: leads-backend
    container_name: leads-backend
    env_file: .env.staging
    environment:
      <<: *app-env
    volumes:
      - sail-storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy 
    networks: [sail]
  
  queue:
    image: leads-backend
    container_name: leads-queue
    command: php artisan queue:work --verbose --timeout=120 --memory=512 --tries=3
    env_file: .env.staging
    environment:
      <<: *app-env
    volumes:
      - sail-storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy 
    networks: [sail]
    restart: unless-stopped

  frontend:
    build:
      context: ../lead-import-visualizer 
      dockerfile: Dockerfile            
    image: leads-frontend
    container_name: leads-frontend
    
    ports:
      - "8080:80" 
    networks: [sail]
    depends_on: [laravel]

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
  sail-storage: 

