server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Permite uploads maiores
    client_max_body_size 100m;
    client_body_timeout 120s;

    location / {
        try_files $uri /index.html;
    }

    # Use /api/ (com barra) para casar melhor e evite bufferar upload
    location /api/ {
        proxy_pass http://laravel;               # serviço do backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_request_buffering off;             # <--- importante para arquivos grandes
    }

    location /sanctum {
        proxy_pass http://laravel;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_request_buffering off;
    }
}
