; CLI – pensado para jobs leves
max_execution_time = 0
memory_limit = 112M

; Upload/POST
upload_max_filesize = 128M
post_max_size = 128M
max_input_time = -1

; Mantemos opcache desativado no CLI para poupar memória.
opcache.enable_cli = 0
