; CLI – reports/prévias (XLSX)
max_execution_time = 0
memory_limit = 320M     ; acompanha o --memory=320 e mem_limit 352m

upload_max_filesize = 128M
post_max_size = 128M
max_input_time = -1

opcache.enable_cli = 0
