; CLI – FGTS (alta prioridade, planilhas/spool)
max_execution_time = 0
memory_limit = 832M   ; ~93% do mem_limit do container

upload_max_filesize = 128M
post_max_size = 128M
max_input_time = -1

opcache.enable_cli = 0
